// GENERATED by image_variants.py alongside products.ts. Do not hand-edit.
// Original size of every site image and the WebP widths that exist for it.
// An image missing from this list is served as its plain JPEG.
export interface ImageInfo {
  w: number;
  h: number;
  webp: number[];
  mobile?: { w: number; h: number; webp: number[] };
}

export const imageManifest: Record<string, ImageInfo> = {
  "/images/afnan-9pm-nightout-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/afnan-9pm-rebel-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/afnan-supremacy-collectors-edition-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/al-rehab-choco-musk-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/amouance-existia-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/amouance-guideon-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/amouance-guideon-46-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/amouance-love-bright-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/armaf-club-de-nuit-iconic-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/armaf-club-de-nuit-intense-man-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/armaf-club-de-nuit-malyka-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/armaf-yum-yum-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/aro-fac-suger-lollipop-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/aro-fac-suger-rush-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/category-men.jpg": {
    "w": 1200,
    "h": 900,
    "webp": [
      480,
      800,
      1200
    ]
  },
  "/images/category-unisex.jpg": {
    "w": 1200,
    "h": 900,
    "webp": [
      480,
      800,
      1200
    ]
  },
  "/images/category-women.jpg": {
    "w": 1200,
    "h": 900,
    "webp": [
      480,
      800,
      1200
    ]
  },
  "/images/clive-dorris-angham-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/clive-dorris-now-black-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-eden-juicy-apple-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-eden-plush-pear-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-eden-sparkling-lychee-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-the-wedding-silk-santal-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-vanilla-candy-rock-sugar-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-yum-boujee-marshmallow-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/elysia-yum-pistachio-gelato-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/hero-jayda.jpg": {
    "w": 2400,
    "h": 1000,
    "webp": [
      1024,
      1600,
      2400
    ],
    "mobile": {
      "w": 1000,
      "h": 1000,
      "webp": [
        600,
        1000
      ]
    }
  },
  "/images/lattafa-asad-bourbon-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/lattafa-eclaire-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/lattafa-eclaire-banoffi-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/lattafa-eclaire-pistache-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/lattafa-yara-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/lattafa-yara-candy-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/paris-corner-marshmallow-blush-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/prefer-love-vanilla-voyage-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  },
  "/images/rave-now-women-1.jpg": {
    "w": 1200,
    "h": 1200,
    "webp": [
      400,
      800,
      1200
    ]
  }
};
